server:
  port: 8080

spring:
  sql:
    init:
      mode: always
      platform: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/management
    username: root
    password: passMQ5&
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true # Show SQL statements
    hibernate:
      ddl-auto: update # Validate the database schema automatically
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true # Format SQL statements

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

jwt:
  private:
    key: classpath:rsa.private.key
  public:
    key: classpath:rsa.public.key

resources:
  image:
    shepard-face: classpath:imgFaceShepard.txt

application:
  client:
    endpoint:
      method:
        protocol: http
        host: www.solutions.com
        port: 8080
        basePath: /endpoint/api/method
        timeout:
          connection: 300000
          read: 300000
        url: ${application.client.endpoint.method.protocol}://${application.client.endpoint.method.host}:${application.client.endpoint.method.port}${application.client.endpoint.method.basePath}

logging:
  level:
    root: info
    org.springframework.web: info
    org.springframework.security: info
